title: シャドバトラッカー
description: トークンカウント・戦績記録・メタゲームなどの機能を通じて、シャドバWBユーザーの勝率UPを助ける

plugins:
  - jekyll-remote-theme
  - jekyll-feed

remote_theme: PQuod/simply-cyan-theme

show_dark_mode: true
paginate: 0